name: Code Quality and Tests
on: [push]
jobs:
  lint:
    name: ✅ Lint
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install dependencies and lint
        run: |
          npm ci
          npm run lint
  dep-check:
    name: ✅ Check Dependencies
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install and check dependencies
        run: |
          npm ci
          npm run deps:check
  test:
    name: 🧪 Unit Test
    runs-on: ubuntu-latest
    needs: [lint, dep-check]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install dependencies and run tests
        run: |
          npm ci
          npm test
